alias: Pixelit Timer
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.alexa_next_timer
    id: next_timer
condition: []
action:
  - repeat:
      while:
        - condition: template
          value_template: >-
            {{ states(trigger.entity_id) != 'unavailable' and
            as_datetime(states(trigger.entity_id)) >= now() }}
      sequence:
        - parallel:
            - delay:
                hours: 0
                minutes: 0
                seconds: 1
            - service: rest_command.pixelit_timer
              data:
                message: >-
                  {{ (today_at("00:00")+(as_datetime(states(trigger.entity_id))
                  - now())).timestamp() | timestamp_custom("%H:%M") if
                  ((today_at("00:00")+(as_datetime(states(trigger.entity_id)) -
                  now())).hour) > 0 else
                  (today_at("00:00")+(as_datetime(states(trigger.entity_id)) -
                  now())).timestamp() | timestamp_custom("%M:%S") }}
                red: 250
                green: 250
                blue: 250
mode: single
