substitutions:
  device_name: washing-machine
  friendly_name: Washing Machine
  main_icon: "washing-machine"
  default_state: "RESTORE_DEFAULT_ON"
  activity_threshold: "5"
  
<<: !include base/gosund-up111.yaml